# Generated by Django 3.0.8 on 2020-07-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('5', 'تسلط کامل')], default='1', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(related_name='skills', to='userProfile.Skills'),
        ),
    ]
