# Generated by Django 3.0.8 on 2020-07-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_auto_20200706_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(choices=[('5', 'تسلط کامل'), ('4', 'زیاد'), ('3', 'متوسط'), ('2', 'کم'), ('1', 'در حد آشنایی')], default='1', max_length=1),
        ),
    ]
