# Generated by Django 2.2 on 2020-07-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_auto_20200714_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='update',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
