# Generated by Django 3.0.8 on 2020-07-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_auto_20200706_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
