# Generated by Django 3.0.8 on 2020-07-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_auto_20200706_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='name',
            new_name='title',
        ),
    ]
