# Generated by Django 3.0.8 on 2020-07-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_auto_20200706_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='title',
            new_name='education_title',
        ),
    ]
