# Generated by Django 3.0.8 on 2020-07-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0009_auto_20200706_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='education_title',
            new_name='title',
        ),
    ]
